### ISSUE TITLE
Output y_50, y_90, y_99, y_99.9

### ISSUE THREAD

**Issue by fnaji** [tercen/nonlinear_regression_operator#1]
Currently, it is outputting x_50, x_90, x_99, x_99.9,  user would like the y values instead

**Comment by agouy** [comment]
@fnaji These values can be obtained by multiplying Bmax by 0.5, 0.9, etc. Is it really necessary to include them as an output of the operator?
To be sure we are on the same page, x_50 is the value of x when y is 50% of y_max (or b_max)

**Comment by CRStevens54** [comment]
Hi @agouy, 
The original output should be Bmax from the Y axis.  We are not doing a concentration curve where we want to know the concentration that we hit saturation.  We need to know what MFI (Y axis) the curve saturation occurs.  This is then used for a second analysis and calculation.  I appreciate the help with this and love what you've done so far.

**Comment by agouy** [comment]
Hi @CRStevens54 @fnaji 
Thanks for the clarification! version 0.0.9 of the operator now outputs y values, closing this issue.
